version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digit-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./results:/app/results

  demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digit-demo
    command: ["python", "-m", "streamlit", "run", "app/streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./results:/app/results
    depends_on:
      - api
